### ISSUE TITLE
MissingPluginException(No implementation found for method jump2act on channel com.jzhu.jump/plugin)

### ISSUE THREAD

**Issue by jp1017** [zhujian1989/MyArchitecture#3]
遇到这个错误：

`MissingPluginException(No implementation found for method jump2act on channel com.jzhu.jump/plugin)`

产生原因是, 在 `pubspec.yaml` 添加了三个依赖:

```
dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 0.4.3
  fluttertoast: 2.2.7
  path_provider: 0.5.0
```
